CREATE DATABASE IF NOT EXISTS `porto-08` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `porto-08`;

CREATE TABLE IF NOT EXISTS cursos (
  id_curso INT AUTO_INCREMENT PRIMARY KEY,
  nome_curso VARCHAR(100) NOT NULL,
  descricao TEXT NULL,
  carga_horaria INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_cursos_nome UNIQUE (nome_curso)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS professores (
  id_professor INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  especialidade VARCHAR(100) NULL,
  email VARCHAR(100) NULL,
  telefone VARCHAR(20) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_professores_email UNIQUE (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS turmas (
  id_turma INT AUTO_INCREMENT PRIMARY KEY,
  nome_turma VARCHAR(50) NOT NULL,
  ano INT NOT NULL,
  id_curso INT NULL,
  id_professor INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_turmas_cursos FOREIGN KEY (id_curso) REFERENCES cursos (id_curso) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_turmas_professores FOREIGN KEY (id_professor) REFERENCES professores (id_professor) ON UPDATE CASCADE ON DELETE SET NULL,
  INDEX idx_turmas_id_curso (id_curso),
  INDEX idx_turmas_id_professor (id_professor)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS alunos (
  id_aluno INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  data_nascimento DATE NULL,
  email VARCHAR(100) NULL,
  telefone VARCHAR(20) NULL,
  id_turma INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_alunos_email UNIQUE (email),
  CONSTRAINT fk_alunos_turmas FOREIGN KEY (id_turma) REFERENCES turmas (id_turma) ON UPDATE CASCADE ON DELETE SET NULL,
  INDEX idx_alunos_id_turma (id_turma)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  papel ENUM('ADMIN', 'PROFESSOR', 'ALUNO') NOT NULL DEFAULT 'ADMIN',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_usuarios_email UNIQUE (email)
) ENGINE=InnoDB;